package com.elink.evco.platform.iam.service.impl;

import java.util.List;

/**
 * 菜单目录（P1 全量 73 项）：与《充电运营平台菜单架构 v4.1》一二级三级命名完全对齐。
 *
 * <p>DEC-20260820-015：目录由「按交付周追加」改为一次全量登记；未交付周页面由前端渲染骨架占位页。
 * 叶子菜单携带入口权限码（resource:read），与 iam_permission.menu_path 一一对应；
 * 权限全量 ACTIVE 入库（V202608240006）后，超级管理员登录即见全部 P1 菜单。
 * P2 企业客户管理平台 9 菜单为独立应用（W7 交付），不在本目录；待前端骨架页确定后评估是否迁移入 iam_menu 表。
 */
public final class MenuCatalog {

    /** 工具类禁止实例化。 */
    private MenuCatalog() {}

    /** 菜单定义节点；叶子（permission 非空）无子级，父级节点无路由。 */
    record MenuDef(
            String key, String title, String path, String permission, List<MenuDef> children) {}

    /** P1 菜单树全量（运营总览 → 系统与配置，按菜单架构 v4.1 顺序）。 */
    static final List<MenuDef> TREE =
            List.of(
                    // 一级：运营总览（无二级，三级直挂）
                    group(
                            "operation-overview",
                            "运营总览",
                            leaf(
                                    "operation-overview",
                                    "运营概览",
                                    "/operation-overview/operation-overview",
                                    "operation_overview:read"),
                            leaf(
                                    "todo-warning",
                                    "待办与预警",
                                    "/operation-overview/todo-warning",
                                    "todo_warning:read")),
                    // 一级：场站与运维
                    group(
                            "station-maintenance",
                            "场站与运维",
                            group(
                                    "asset-management",
                                    "资产管理",
                                    leaf(
                                            "station",
                                            "场站管理",
                                            "/station-maintenance/asset-management/station",
                                            "station:read"),
                                    leaf(
                                            "device",
                                            "设备管理",
                                            "/station-maintenance/asset-management/device",
                                            "device:read"),
                                    leaf(
                                            "asset-field-template",
                                            "资产字段模板",
                                            "/station-maintenance/asset-management/asset-field-template",
                                            "asset_field_template:read")),
                            group(
                                    "station-service",
                                    "场站服务",
                                    leaf(
                                            "service-config",
                                            "服务配置",
                                            "/station-maintenance/station-service/service-config",
                                            "service_config:read"),
                                    leaf(
                                            "parking-service",
                                            "停车服务协同",
                                            "/station-maintenance/station-service/parking-service",
                                            "parking_service:read"),
                                    leaf(
                                            "access-parking",
                                            "出入口与车位协同",
                                            "/station-maintenance/station-service/access-parking",
                                            "access_parking:read"),
                                    leaf(
                                            "campus-service",
                                            "园区便民服务协同",
                                            "/station-maintenance/station-service/campus-service",
                                            "campus_service:read"),
                                    leaf(
                                            "scheduled-charging",
                                            "场站定时充电策略",
                                            "/station-maintenance/station-service/scheduled-charging",
                                            "scheduled_charging:read")),
                            group(
                                    "operation-maintenance",
                                    "运行维护",
                                    leaf(
                                            "real-time-monitor",
                                            "实时监控",
                                            "/station-maintenance/operation-maintenance/real-time-monitor",
                                            "real_time_monitor:read"),
                                    leaf(
                                            "station-data-analysis",
                                            "场站数据分析",
                                            "/station-maintenance/operation-maintenance/station-data-analysis",
                                            "station_data_analysis:read"),
                                    leaf(
                                            "device-data-analysis",
                                            "设备数据分析",
                                            "/station-maintenance/operation-maintenance/device-data-analysis",
                                            "device_data_analysis:read"),
                                    leaf(
                                            "device-protocol-trace",
                                            "设备协议追溯",
                                            "/station-maintenance/operation-maintenance/device-protocol-trace",
                                            "device_protocol_trace:read"),
                                    leaf(
                                            "alarm",
                                            "告警管理",
                                            "/station-maintenance/operation-maintenance/alarm",
                                            "alarm:read"),
                                    leaf(
                                            "ops-ticket",
                                            "运维工单",
                                            "/station-maintenance/operation-maintenance/ops-ticket",
                                            "ops_ticket:read"),
                                    leaf(
                                            "remote-operation-record",
                                            "远程操作记录",
                                            "/station-maintenance/operation-maintenance/remote-operation-record",
                                            "remote_operation_record:read"))),
                    // 一级：客户与权益
                    group(
                            "customer-equity",
                            "客户与权益",
                            group(
                                    "personal-customer",
                                    "个人客户",
                                    leaf(
                                            "personal-user",
                                            "个人用户",
                                            "/customer-equity/personal-customer/personal-user",
                                            "personal_user:read"),
                                    leaf(
                                            "member-benefit",
                                            "会员与权益",
                                            "/customer-equity/personal-customer/member-benefit",
                                            "member_benefit:read")),
                            group(
                                    "enterprise-customer",
                                    "企业客户",
                                    leaf(
                                            "enterprise",
                                            "企业管理",
                                            "/customer-equity/enterprise-customer/enterprise",
                                            "enterprise:read"),
                                    leaf(
                                            "enterprise-member",
                                            "企业成员账户",
                                            "/customer-equity/enterprise-customer/enterprise-member",
                                            "enterprise_member:read"),
                                    leaf(
                                            "enterprise-vehicle",
                                            "企业车辆管理",
                                            "/customer-equity/enterprise-customer/enterprise-vehicle",
                                            "enterprise_vehicle:read"),
                                    leaf(
                                            "enterprise-evcard",
                                            "企业电卡管理",
                                            "/customer-equity/enterprise-customer/enterprise-evcard",
                                            "enterprise_evcard:read")),
                            group(
                                    "partner-operation",
                                    "合作运营",
                                    leaf(
                                            "tenant",
                                            "租户管理",
                                            "/customer-equity/partner-operation/tenant",
                                            "tenant:read"),
                                    leaf(
                                            "partner",
                                            "合作方管理",
                                            "/customer-equity/partner-operation/partner",
                                            "partner:read"))),
                    // 一级：交易与售后
                    group(
                            "transaction-after-sales",
                            "交易与售后",
                            group(
                                    "charging-transaction",
                                    "充电交易",
                                    leaf(
                                            "charging-order",
                                            "充电订单",
                                            "/transaction-after-sales/charging-transaction/charging-order",
                                            "charging_order:read"),
                                    leaf(
                                            "occupancy-reminder",
                                            "占位提醒",
                                            "/transaction-after-sales/charging-transaction/occupancy-reminder",
                                            "occupancy_reminder:read")),
                            group(
                                    "after-sales",
                                    "售后服务",
                                    leaf(
                                            "refund-difference",
                                            "退款与补差",
                                            "/transaction-after-sales/after-sales/refund-difference",
                                            "refund_difference:read"),
                                    leaf(
                                            "customer-service-appeal",
                                            "客服与申诉",
                                            "/transaction-after-sales/after-sales/customer-service-appeal",
                                            "customer_service_appeal:read"))),
                    // 一级：计费与营销
                    group(
                            "billing-marketing",
                            "计费与营销",
                            group(
                                    "billing-management",
                                    "计费管理",
                                    leaf(
                                            "charging-billing",
                                            "充电计费管理",
                                            "/billing-marketing/billing-management/charging-billing",
                                            "charging_billing:read"),
                                    leaf(
                                            "enterprise-agreement-price",
                                            "企业协议价",
                                            "/billing-marketing/billing-management/enterprise-agreement-price",
                                            "enterprise_agreement_price:read"),
                                    leaf(
                                            "purchase-sale-price",
                                            "购售电价",
                                            "/billing-marketing/billing-management/purchase-sale-price",
                                            "purchase_sale_price:read")),
                            group(
                                    "marketing-equity",
                                    "营销权益",
                                    leaf(
                                            "marketing-campaign",
                                            "营销活动",
                                            "/billing-marketing/marketing-equity/marketing-campaign",
                                            "marketing_campaign:read"),
                                    leaf(
                                            "coupon-campaign",
                                            "发券活动",
                                            "/billing-marketing/marketing-equity/coupon-campaign",
                                            "coupon_campaign:read"),
                                    leaf(
                                            "recharge-campaign",
                                            "充值活动",
                                            "/billing-marketing/marketing-equity/recharge-campaign",
                                            "recharge_campaign:read"),
                                    leaf(
                                            "charging-campaign",
                                            "充电活动",
                                            "/billing-marketing/marketing-equity/charging-campaign",
                                            "charging_campaign:read"),
                                    leaf(
                                            "point-campaign",
                                            "积分活动",
                                            "/billing-marketing/marketing-equity/point-campaign",
                                            "point_campaign:read"),
                                    leaf(
                                            "precision-marketing",
                                            "精准营销",
                                            "/billing-marketing/marketing-equity/precision-marketing",
                                            "precision_marketing:read"),
                                    leaf(
                                            "coupon-asset",
                                            "优惠资产与核销",
                                            "/billing-marketing/marketing-equity/coupon-asset",
                                            "coupon_asset:read"))),
                    // 一级：资金与结算
                    group(
                            "fund-settlement",
                            "资金与结算",
                            group(
                                    "personal-fund",
                                    "个人资金",
                                    leaf(
                                            "personal-fund-management",
                                            "个人资金管理",
                                            "/fund-settlement/personal-fund/personal-fund-management",
                                            "personal_fund:read"),
                                    leaf(
                                            "personal-transaction",
                                            "个人交易明细",
                                            "/fund-settlement/personal-fund/personal-transaction",
                                            "personal_transaction:read")),
                            group(
                                    "enterprise-fund",
                                    "企业资金",
                                    leaf(
                                            "enterprise-fund-account",
                                            "企业资金账户",
                                            "/fund-settlement/enterprise-fund/enterprise-fund-account",
                                            "enterprise_fund_account:read"),
                                    leaf(
                                            "enterprise-recharge",
                                            "企业充值明细",
                                            "/fund-settlement/enterprise-fund/enterprise-recharge",
                                            "enterprise_recharge:read")),
                            group(
                                    "tenant-settlement",
                                    "租户结算",
                                    leaf(
                                            "settlement-account",
                                            "结算账户管理",
                                            "/fund-settlement/tenant-settlement/settlement-account",
                                            "settlement_account:read"),
                                    leaf(
                                            "station-settlement-plan",
                                            "场站结算方案",
                                            "/fund-settlement/tenant-settlement/station-settlement-plan",
                                            "station_settlement_plan:read"),
                                    leaf(
                                            "tenant-settlement-bill",
                                            "租户结算账单",
                                            "/fund-settlement/tenant-settlement/tenant-settlement-bill",
                                            "tenant_settlement_bill:read"),
                                    leaf(
                                            "payment-receipt",
                                            "付款与回单",
                                            "/fund-settlement/tenant-settlement/payment-receipt",
                                            "payment_receipt:read")),
                            group(
                                    "accounting-invoice",
                                    "账务与票据",
                                    leaf(
                                            "channel-reconciliation",
                                            "渠道与账务对账",
                                            "/fund-settlement/accounting-invoice/channel-reconciliation",
                                            "channel_reconciliation:read"),
                                    leaf(
                                            "user-charging-invoice",
                                            "用户充电发票",
                                            "/fund-settlement/accounting-invoice/user-charging-invoice",
                                            "user_charging_invoice:read"),
                                    leaf(
                                            "tenant-incoming-invoice",
                                            "租户来票管理",
                                            "/fund-settlement/accounting-invoice/tenant-incoming-invoice",
                                            "tenant_incoming_invoice:read"),
                                    leaf(
                                            "platform-service-invoice",
                                            "平台服务费发票",
                                            "/fund-settlement/accounting-invoice/platform-service-invoice",
                                            "platform_service_invoice:read"))),
                    // 一级：V2G 运营
                    group(
                            "v2g-operation",
                            "V2G运营",
                            group(
                                    "discharge-operation",
                                    "放电运营",
                                    leaf(
                                            "discharge-authorization",
                                            "放电授权与策略",
                                            "/v2g-operation/discharge-operation/discharge-authorization",
                                            "discharge_authorization:read"),
                                    leaf(
                                            "discharge-order",
                                            "放电订单",
                                            "/v2g-operation/discharge-operation/discharge-order",
                                            "discharge_order:read")),
                            group(
                                    "discharge-settlement",
                                    "放电结算",
                                    leaf(
                                            "discharge-pricing",
                                            "放电价格与计费",
                                            "/v2g-operation/discharge-settlement/discharge-pricing",
                                            "discharge_pricing:read"),
                                    leaf(
                                            "discharge-settlement",
                                            "放电结算与对账",
                                            "/v2g-operation/discharge-settlement/discharge-settlement",
                                            "discharge_settlement:read")),
                            group(
                                    "discharge-monitor",
                                    "放电监控",
                                    leaf(
                                            "discharge-monitor-analysis",
                                            "放电监控与分析",
                                            "/v2g-operation/discharge-monitor/discharge-monitor-analysis",
                                            "discharge_monitor_analysis:read"))),
                    // 一级：数据分析
                    group(
                            "data-analysis",
                            "数据分析",
                            group(
                                    "business-analysis",
                                    "经营分析",
                                    leaf(
                                            "business-analysis-report",
                                            "经营分析与报表",
                                            "/data-analysis/business-analysis/business-analysis-report",
                                            "business_analysis_report:read"),
                                    leaf(
                                            "revenue-analysis",
                                            "收益分析",
                                            "/data-analysis/business-analysis/revenue-analysis",
                                            "revenue_analysis:read")),
                            group(
                                    "asset-analysis",
                                    "资产分析",
                                    leaf(
                                            "asset-ops-analysis",
                                            "资产与运维分析",
                                            "/data-analysis/asset-analysis/asset-ops-analysis",
                                            "asset_ops_analysis:read"))),
                    // 一级：监管接入
                    group(
                            "regulatory-access",
                            "监管接入",
                            group(
                                    "regulatory-operation",
                                    "监管运营",
                                    leaf(
                                            "regulatory-archive",
                                            "监管业务档案",
                                            "/regulatory-access/regulatory-operation/regulatory-archive",
                                            "regulatory_archive:read"),
                                    leaf(
                                            "regulatory-report",
                                            "监管报送与补推",
                                            "/regulatory-access/regulatory-operation/regulatory-report",
                                            "regulatory_report:read"),
                                    leaf(
                                            "regulatory-reconciliation",
                                            "监管对账与异常",
                                            "/regulatory-access/regulatory-operation/regulatory-reconciliation",
                                            "regulatory_reconciliation:read"))),
                    // 一级：系统与配置
                    group(
                            "system-config",
                            "系统与配置",
                            group(
                                    "permission-management",
                                    "权限管理",
                                    leaf(
                                            "platform-admin",
                                            "平台管理员",
                                            "/system-config/permission-management/platform-admin",
                                            "iam_user:read"),
                                    leaf(
                                            "tenant-permission",
                                            "租户权限分配",
                                            "/system-config/permission-management/tenant-permission",
                                            "tenant_permission:read"),
                                    leaf(
                                            "marketing-permission",
                                            "营销权限",
                                            "/system-config/permission-management/marketing-permission",
                                            "mkt_permission:read"),
                                    leaf(
                                            "auth-audit",
                                            "授权审计",
                                            "/system-config/permission-management/auth-audit",
                                            "auth_audit:read")),
                            group(
                                    "app-content",
                                    "应用与内容",
                                    leaf(
                                            "mini-program",
                                            "小程序管理",
                                            "/system-config/app-content/mini-program",
                                            "mini_program:read"),
                                    leaf(
                                            "mini-program-content",
                                            "小程序内容配置",
                                            "/system-config/app-content/mini-program-content",
                                            "mini_program_content:read"),
                                    leaf(
                                            "dashboard-config",
                                            "运营大屏配置与发布",
                                            "/system-config/app-content/dashboard-config",
                                            "dashboard_config:read"),
                                    leaf(
                                            "message-notice",
                                            "消息与公告配置",
                                            "/system-config/app-content/message-notice",
                                            "message_notice:read")),
                            group(
                                    "trade-config",
                                    "交易配置",
                                    leaf(
                                            "payment-channel",
                                            "支付渠道与路由",
                                            "/system-config/trade-config/payment-channel",
                                            "payment_channel:read"),
                                    leaf(
                                            "settlement-channel",
                                            "结算渠道配置",
                                            "/system-config/trade-config/settlement-channel",
                                            "settlement_channel:read")),
                            group(
                                    "base-setting",
                                    "基础设置",
                                    leaf(
                                            "platform-setting",
                                            "基础设置",
                                            "/system-config/base-setting/platform-setting",
                                            "platform_setting:read"))));

    /**
     * 构造叶子菜单定义。
     *
     * @param key 菜单标识。
     * @param title 菜单中文名。
     * @param path 三级路由。
     * @param permission 入口权限码。
     * @return 叶子菜单定义。
     */
    private static MenuDef leaf(String key, String title, String path, String permission) {
        return new MenuDef(key, title, path, permission, List.of());
    }

    /**
     * 构造父级菜单定义。
     *
     * @param key 菜单标识。
     * @param title 菜单中文名。
     * @param children 子菜单集合。
     * @return 父级菜单定义。
     */
    private static MenuDef group(String key, String title, MenuDef... children) {
        return new MenuDef(key, title, null, null, List.of(children));
    }
}
