spring:
  application:
    name: device-connectivity-service
  main:
    banner-mode: "off"
server:
  port: ${EVCO_DEVICE_CONNECTIVITY_SERVER_PORT:8083}
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: false
